### PR TITLE
samplename order fix

### PR DESCRIPTION
**Pull request by roryk**
Some folks at AZ noticed that sometimes the sampleNames can get applied to the wrong files, for example:

```
                                                                               AS_1
"/bigseq/analysis/20190305_CVRM_TweakFn4_SOUK003803_bcbio/final/AS_10/salmon/quant.sf"
                                                                                AS_10
"/bigseq/analysis/20190305_CVRM_TweakFn4_SOUK003803_bcbio/final/AS_11/salmon/quant.sf"
                                                                                AS_11
"/bigseq/analysis/20190305_CVRM_TweakFn4_SOUK003803_bcbio/final/AS_12/salmon/quant.sf"
                                                                                AS_12
"/bigseq/analysis/20190305_CVRM_TweakFn4_SOUK003803_bcbio/final/AS_1/salmon/quant.sf"
                                                                                 AS_2
"/bigseq/analysis/20190305_CVRM_TweakFn4_SOUK003803_bcbio/final/AS_2/salmon/quant.sf"
                                                                                 AS_3
"/bigseq/analysis/20190305_CVRM_TweakFn4_SOUK003803_bcbio/final/AS_3/salmon/quant.sf"
                                                                                 AS_4
"/bigseq/analysis/20190305_CVRM_TweakFn4_SOUK003803_bcbio/final/AS_4/salmon/quant.sf"
                                                                                 AS_5
"/bigseq/analysis/20190305_CVRM_TweakFn4_SOUK003803_bcbio/final/AS_5/salmon/quant.sf"
                                                                                 AS_6
"/bigseq/analysis/20190305_CVRM_TweakFn4_SOUK003803_bcbio/final/AS_6/salmon/quant.sf"
                                                                                 AS_7
"/bigseq/analysis/20190305_CVRM_TweakFn4_SOUK003803_bcbio/final/AS_7/salmon/quant.sf"
                                                                                 AS_8
"/bigseq/analysis/20190305_CVRM_TweakFn4_SOUK003803_bcbio/final/AS_8/salmon/quant.sf"
                                                                                 AS_9
"/bigseq/analysis/20190305_CVRM_TweakFn4_SOUK003803_bcbio/final/AS_9/salmon/quant.sf"
```

the list.files function doesn't put them in any particular order, so here we sort the sampleNames and then sort the files to put them in the right order.

### CODE REVIEW

**Comment by roryk** [comment]
This fixed it for me in a toy thing I made, but I didn't do all the tests. Opening up a p/r so I can make sure the tests still pass.

**Comment by mjsteinbaugh** [comment]
Thanks @roryk

**Comment by mjsteinbaugh** [comment]
I made a couple of tweaks to the AppVeyor config, to include testing against the previous release version.

**Comment by roryk** [comment]
Did you ever figure out the resolution to that GenomeInfoDbData not getting found by bioconductor issue? We're running into that here with travis. I poked around and saw you had a back and forth about it a few years back.

**Comment by roryk** [comment]
Thanks. How did you push to this pull request? You did magic.

**Comment by mjsteinbaugh** [comment]
Let me check my notes about that. Otherwise, take a look at the fork I've been testing: https://github.com/acidgenomics/bcbioRNASeq

**Comment by mjsteinbaugh** [comment]
I switched to using a Docker image for Travis because I was running into too many configuration and timeout issues.

**Comment by mjsteinbaugh** [comment]
Yeah you can [see here](https://github.com/acidgenomics/bcbioRNASeq/blob/master/R/tximport-internal.R#L46) a reworked approach that avoids the need to use `list.files()`. I think this is a better way to go.

**Comment by roryk** [comment]
> Yeah you can [see here](https://github.com/acidgenomics/bcbioRNASeq/blob/master/R/tximport-internal.R#L46) a reworked approach that avoids the need to use `list.files()`. I think this is a better way to go.

Yup, agreed. I'll swap to that.

**Comment by roryk** [comment]
I'm cool for dropping R 3.4 support-- bioconda is onto 3.5 so we don't have a need to be on 3.4 anymore.

**Comment by mjsteinbaugh** [comment]
That makes unit testing easier -- let's pin to R 3.5 instead then.

**Comment by roryk** [comment]
THANK YOU SO MUCH, it would have taken me forever to figure out how to get the tests working.

**Comment by mjsteinbaugh** [comment]
@roryk I got Docker working for the HBC R packages, so if we run into Travis build time and cache issues, we can switch over to using those images. For now let's stick with testing the code against macOS on R 3.5.

**Comment by roryk** [comment]
Awesome, thanks so much.

**Comment by roryk** [comment]
Going to cut a new release and update the bioconda recipe now.

**Pull request merged**
