### PR TITLE
v0.2.5

### PR DESCRIPTION
**Pull request by mjsteinbaugh**
@roryk This should work for testing bcbio integration.

## Minor changes

- Enable support bcbio integration, by modifying `bcbioRNASeq()` constructor
  to work with minimal bcbio test data.
- Switched from internal usage of `aes_()` in favor of consistent usage of
  `aes_string()`. This will make the transition to [ggplot2][] v2.3.0 easier
  in a future update.

### CODE REVIEW

**Review by roryk — APPROVED** [review]
Looks good to me!

**Comment by roryk** [comment]
Looks like `bioc-devel` is failing

**Comment by roryk** [comment]
Maybe need to revert https://github.com/hbc/bcbioRNASeq/pull/104/commits/03ab682ec0858c33fa26a99625bee98143ee0258 ?

**Comment by mjsteinbaugh** [comment]
Okay this should be good to go now.

**Review by lpantano — APPROVED** [review]

**Comment by roryk** [comment]
Appveyor still borked, looks like the issue is building against devel, can we just build against release?

**Comment by mjsteinbaugh** [comment]
@roryk Okay Travis and AppVeyor should both be good to go now

**Comment by roryk** [comment]
Awesome! Thanks so much Mike.

**Pull request merged**
