### PR TITLE
0.0.26

### PR DESCRIPTION
**Pull request by mjsteinbaugh**
- Renamed package from bcbioRnaseq to bcbioRNASeq.
- Renamed `plotDispersion()` to `plotDispEsts()`.
- Upgraded basejump dependency to 0.0.22. This now uses `prepareSummarizedExperiment()` instead of `prepareSE()`.
- Quality control plotting functions now use viridis color palette.
- Heatmaps now use inferno color palette, with viridis labels.
- Fixed `alphaSummary()` to better handle `contrast` and `name` arguments to `DESeq2::results()`.
- Fixed working examples that use `meltLog10()`, defaulting to TMM counts.
- Restricted passthroughs to `pheatmap()` on heatmap plotting functions. This can cause unexpected output otherwise. We can add this back with proper unit testing.
- Appearance of `plotCountDensity()` has been improved by using fill instead of line color.
- Website has been upgraded to use readable bootswatch theme.
- Plot legends are now kept for `plotMeanSD()`.
- Fixed capitalization of mouse gender markers.

### CODE REVIEW

**Comment by lpantano** [comment]
Are the templates changed with the names of the new functions?

**Comment by mjsteinbaugh** [comment]
Should be updated – the only function I changed is `plotDispEsts()`, to match `BiocGenerics::plotDispEsts()` instead of using our own generic.

**Comment by lpantano** [comment]
I see templates and setup.R and doing `library(bcbioRnaseq)` with the old name, that should be changed right?

**Comment by lpantano** [comment]
I just pushed a couple of fixes. The only question I have is whether this URL is the valid one or not:

http://bioinformatics.sph.harvard.edu/bcbioRNASeq

**Comment by lpantano** [comment]
The error in travis is new, Dont' know what this means:

> Warning: multiple methods tables found for ‘Ontology’

**Comment by mjsteinbaugh** [comment]
Once we merge the changes, the URL will work. I already updated this for the single cell code: http://bioinformatics.sph.harvard.edu/bcbioSingleCell/

**Comment by mjsteinbaugh** [comment]
@lpantano I'm guessing that Ontology methods table warning has something to do with a Bioconductor package that gets loaded when we attach SummarizedExperiment. I'll check it out, but it shouldn't be anything directly related to our code.

**Review by lpantano — APPROVED** [review]

**Pull request merged**
