### PR TITLE
v0.2.4

### PR DESCRIPTION
**Pull request by mjsteinbaugh**
## Major changes

- `aggregateReplicates()` support has been added back. This function returns
  a `RangedSummarizedExperiment` instead of a `bcbioRNASeq` object, containing
  only an aggregate raw counts matrix in the `counts` slot of `assays()`.
- The functional analysis [R Markdown][] template has been reworked to use
  `dds_file` and `organism` as new parameter arguments. We've reduced the number
  of parameters required here to run [clusterProfiler][].
- Made `alphaSummary()` defunct for `bcbioRNASeq` object, in favor of
  `DESeqDataSet` only. This function is only useful when a proper design formula
  has been defined.

## Minor changes

- `metrics()` now contains an informative error for datasets that were analyzed
  using the `fast-rnaseq` [bcbio][] pipeline.
- `DESeqDataSet` coercion from `bcbioRNASeq` object doesn't attempt to run
  `DESeq()` command any more, which was unnecessary and improves speed.
- `bcbioSingleCell()` constructor now supports `censorSamples` parameter. This
  is useful for removing known poor quality samples upon loading.
- [ggplot2][] color and fill palettes are now set `NULL` in the quality control
  functions. This behavior doesn't change the appearance of the plot colors,
  which will still default to `ggplot2::scale_colour_hue()` or
  `ggplot2::scale_fill_hue()`. The upcoming [ggplot2][] v2.3.0 update supports
  global options for color and fill palettes, so these parameters may be
  deprecated in a future release.
- Reworked the internal code for `topTables()`.

## Infrastructure changes

- Added [macOS][] testing to [Travis CI][] build checks.
- Fixed [clusterProfiler][] compilation error on [Travis CI][] by installing
  `libudunits2-dev` (Linux).

### CODE REVIEW

**Comment by mjsteinbaugh** [comment]
clusterProfiler 3.8.1 is failing to compile because of enrichplot and udunits2

```
Installing udunits2
-----Error: libudunits2.a not found-----
     If the udunits2 library is installed in a non-standard location,
     use --configure-args='--with-udunits2-lib=/usr/local/lib' for example,
     or --configure-args='--with-udunits2-include=/usr/include/udunits2'
     replacing paths with appropriate values for your installation.
     You can alternatively use the UDUNITS2_INCLUDE and UDUNITS2_LIB
     environment variables.
     If udunits2 is not installed, please install it.
     It is required for this package.
```

**Comment by mjsteinbaugh** [comment]
clusterProfiler is causing compilation problems on macOS for bioc-release:

```
Error: `pkgs` 'enrichplot', 'GO.db', 'ALL', 'DO.db', 'org.Hs.eg.db' are not installed
```

It's trying to install packages from GitHub rather than using Bioconductor or CRAN binaries.

**Comment by mjsteinbaugh** [comment]
Fixed clusterProfiler compilation issue on Linux by installing `libudunits2-dev`

**Comment by mjsteinbaugh** [comment]
Need to update `test_reports.R` script:

```
test_reports.R:85: error: Functional Analysis
render params not declared in YAML: bcb_file, gspecies, species
1: render(input = "fa.Rmd", params = list(bcb_file = bcb_file, res_file = res_file, 
       organism = "Mm", gspecies = "mmu", species = "mouse", data_dir = data_dir, results_dir = results_dir)) at test_reports.R:85
2: knit_params_get(input_lines, params)
3: stop("render params not declared in YAML: ", paste(invalid_params, collapse = ", "))
```

**Review by lpantano — APPROVED** [review]
it seems all works. I am ok with merging today. Is that ok with you Mike? so tomorrow I can update figures in the paper?

**Comment by mjsteinbaugh** [comment]
Sure let's merge it and then finish the paper figures

**Pull request merged**
