### PR TITLE
0.0.25

### PR DESCRIPTION
**Pull request by mjsteinbaugh**
- Added S4 methods support for plots, allowing the user to use either
  `bcbioRNADataSet` or a metrics `data.frame` and manual `interesting_group`
  declaration for visualization.
- Migrated function and variable names from `snake_case` to `camelCase`.
- Offloaded small RNA functionality to a separate package named [bcbioSmallRna](https://github.com/lpantano/bcbioSmallRna).

### CODE REVIEW

**Review by lpantano — CHANGES_REQUESTED** [review]
what template is `inst/rmarkdown/templates/qc-rnaseq` ? is a new one or we should remove it?

**Review by lpantano — CHANGES_REQUESTED** [review]
in `plotMA` function, add this (rory's commit that got removed):

```
scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10L ^ x),labels = scales::trans_format("log10", scales::math_format(10L ^ .x))) + # nolint
```

see https://github.com/hbc/bcbioRnaseq/commit/400ed15e51ee3690727d5768ec376be70046f8b3

**Review by lpantano — CHANGES_REQUESTED** [review]
In `qc skeleton`, first chunck:

```
# Need to save bcb using `loadRun()` prior to knit!
bcbName <- load(params$bcb)
```
do we have `loadRun` anymore?. What is bcb object? params doesn't have that variable. 

as well:
```
saveData(bcb, dataDir)
```

I'll integrate the data saving in `loadRNASeqRun`:

```
# Load bcbio RNA-seq run
bcb <- loadRNASeqRun(
    uploadDir = params$uploadDir,
    interestingGroups = params$interestingGroups,
    experimentName = params$experimentName,
    researcher = params$researcher,
    principalInvestigator = params$principalInvestigator,
    author = params$author,
    email = params$email,
    cache = params$dataDir
)
```

Internally this function will do:

```
# save if it doesn't exists
saveData(bcb)
# load if it exists
bcbName <- load(params$bcb)
assign("bcb", get(bcbName))
```

If `cache` is not giving, then not cache is performed.

**Review by lpantano — APPROVED** [review]

**Review by roryk — COMMENTED** [review]
I carefully reviewed this and it looks good.

**Review by roryk — APPROVED** [review]

**Pull request merged**
